# Generated by Django 5.2.6 on 2025-11-29 17:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=50)),
                ('cantidad', models.IntegerField()),
                ('marca', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=0, max_digits=15)),
                ('imagen1', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('imagen2', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('imagen3', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.IntegerField(null=True)),
                ('descripcion', models.TextField(max_length=70)),
                ('cantidad', models.IntegerField()),
                ('token', models.CharField(default=uuid.uuid4, max_length=50, unique=True)),
                ('fecha_pedido', models.DateField(auto_now_add=True)),
                ('fecha_necesitado', models.DateField(null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('origen', models.CharField(choices=[('Facebook', 'Facebook'), ('Instagram', 'Instagram'), ('Presencial', 'Presencial'), ('WhatsApp', 'WhatsApp'), ('Sitio Web', 'Sitio Web'), ('TikTok', 'TikTok')], default='Sitio Web', max_length=20)),
                ('estado', models.CharField(choices=[('Solicitado', 'Solicitado'), ('Aprobado', 'Aprobado'), ('En Proceso', 'En Proceso'), ('Realizado', 'Realizado'), ('Entregado', 'Entregado'), ('Finalizado', 'Finalizado'), ('Cancelado', 'Cancelado')], default='Solicitado', max_length=20)),
                ('estado_pago', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Parcial', 'Parcial'), ('Pagado', 'Pagado')], default='Pendiente', max_length=20)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.producto')),
            ],
        ),
    ]
