# Generated by Django 5.2.6 on 2025-11-28 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='fecha_entrega',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
