# Generated by Django 5.2.6 on 2025-12-01 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_alter_pedido_producto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='fecha_necesitado',
            new_name='fecha_entrega_requerida',
        ),
    ]
